### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by hirdrac** [goblinhack/zorbash#2]
Hello - I found your project while doing a search for C++ roguelikes.  Seems very interesting!
Anyways, I managed to build it on my Fedora 34 system but I did run into a few small issues:

1) The root Makefile couldn't find 'RUNME' (the current directory isn't normally in the search path for most systems).  A quick edit of the Makefile to change it to './RUNME' fixed this problem.
2) You seem to be running clang-format on the source as part of the build process.  This caused a lot of files to be changed and made pulling new changes impossible without doing a 'git restore' first.  Seems like it would be better to do clang-format as part of your check-in process (maybe with a new makefile target that could be run manually.)

**Comment by goblinhack** [comment]
He Richard - thanks for the feedback. It's a long way off being complete tho - v work in progress. Probably a year off being a fledged out playable game. Welcome the feedback tho. I've committed those fixes - good points.

**Comment by goblinhack** [comment]
BTW I added a fedora dockerfile - if curious look at RUNME.docker.fedora and docker/fedora.dockerfile - I couldn't find all the audio packages but at least it builds - I use this so I can check fedora builds work

**Comment by hirdrac** [comment]
Interesting.... I've never used docker before but I'll take a look.
