### ISSUE TITLE
build improvements

### ISSUE THREAD

**Issue by hirdrac** [goblinhack/zorbash#3]
Suggestions for improving your current Makefiles (1 small, 1 big):
1) Make sure to use '.PHONY' for all Makefile targets that aren't actual files
2) Object file dependencies are only being created once by build/build.sh with makedepend - no reason you can't change your Makefile to automatically regenerate file dependency info (and also remove need for makedepend).

Here's a sample makefile I created to replace the one generated in src/ (forgive the weird formatting):
`COMPILER_FLAGS = -I/usr/include/SDL2 -I/usr/include/python3.9 -DMYVER=\"0.0.4\" -DPYVER=\"3.9\" -O3`
`CLANG_COMPILER_WARNINGS = -Wall  -std=c++2a`
`GCC_COMPILER_WARNINGS = -x c++ -Wall -std=c++2a`

`LDFLAGS = -rdynamic`
`COMPILER_WARNINGS = $(CLANG_COMPILER_WARNINGS)`
`CC = clang++`

`EXE =`
`DSYM =`
`LDLIBS = -pthread -lSDL2 -lSDL2_mixer -lSDL2_ttf  -L/usr/lib64 -lpython3.9 -lcrypt -lpthread -ldl -lutil -lm -lm -lGL`
`CFLAGS = $(COMPILER_FLAGS) $(COMPILER_WARNINGS)`

`NAME = zorbash-game`
`OBJDIR = .build`

`TARGET_GAME = $(NAME)$(EXE)`
`.PHONY: all`
`all: $(TARGET_GAME)`

`GAME_SOURCE := $(wildcard *.cpp) $(wildcard *.S)`
`GAME_OBJECTS :=\`
`  $(addprefix $(OBJDIR)/,$(addsuffix .o,$(basename $(GAME_SOURCE))))`

`DEP_FILES := $(patsubst %.o,%.d,$(GAME_OBJECTS))`
`DEP_FLAGS = -MMD -MP`

`$(OBJDIR): ; mkdir -p $(OBJDIR)`
`$(GAME_OBJECTS): | $(OBJDIR)`

`$(OBJDIR)/%.o: %.cpp`
&lt;tab>`$(CC) $(EXTRA_CFLAGS) $(CFLAGS) $(DEP_FLAGS) -c -o $@ $<`

`$(OBJDIR)/%.o: %.S`
&lt;tab>`$(CC) $(DEP_FLAGS) -c -o $@ $<`

`# link`
`$(TARGET_GAME): $(GAME_OBJECTS)`
&lt;tab>`$(CC) $(LDFLAGS) $(GAME_OBJECTS) $(LDLIBS) -o $@`

`# format/clean/clobber`
`.PHONY: format clean clobber`

`format:`
&lt;tab>`clang-format -i *cpp *hpp`

`clean:`
&lt;tab>`rm -f ../$(TARGET_GAME) ../stdout.txt ../stderr.txt`
&lt;tab>`rm -f $(TARGET_GAME) stdout.txt stderr.txt`
&lt;tab>`rm -rf $(OBJDIR)`

`clobber: clean`
&lt;tab>`rm -rf $(OBJDIR)`
&lt;tab>`mkdir -p $(OBJDIR)`

`# delete corresponding object file if dependency file needs regeneration`
`$(OBJDIR)/%.d: ; @rm -f "$(@:.d=.o)"`

`# include all dependency files`
`-include $(DEP_FILES)`

Change summary:
1) 'GAME_SOURCE' is defined to contain all your source files (set by wildcard, but it could be a list of files if you don't want to build everything in src/).  object files are never listed directly.
2) GAME_OBJECTS created from GAME_SOURCE
3) DEP_FILES defined to hold a list of all generated dependency files (<source file basename>.d)
4) DEP_FLAGS has compiler flags needed to make g++/clang++ generate a dependency file for each source file while compiling
5) set up makefile targets/dependency to create OBJDIR directory when needed - it doesn't need to be created by clean/clobber any more
6) %.cpp/%.S source file compile rules changed to include DEP_FLAGS
7) when makefile starts up, it tires to include dependency files for all source files.  If any are missing or out-of-date, corresponding objects files are deleted to trigger the creation of new dependency files

**Comment by goblinhack** [comment]
hey nice - you're obviously pretty handy with Makefile syntax. I know just enough to get by :) I'm merged in your changes -see what you think. thanks! I'd forgotten gcc could do the dependancy stuff

**Comment by hirdrac** [comment]
Looks good!  A couple things you still might want to change:
1)  rule for %.S builds needs $(DEP_FLAGS) or it will always build when you 'make all' (go ahead and try it)
2) I moved the $(TARGET_GAME):  rule above all the other targets so 'make' (no args) would default to building the game - without moving it, default make just keeps trying to build ascii_box.o (if you run make while in the src directory)
3) very minor, but your %.cpp/%.S rules suppress the command output (line starting with @) and echo the same line.  if you remove '@' from the start of the command line, you can remove the echo line and get exactly the same output

I spent way too much time over the past few years building my own Makefile based build system that I use in my projects.
Take a look if you're interested:  https://github.com/hirdrac/makefile

**Comment by hirdrac** [comment]
3) move the 'all' target above all the other targets is enough to fix no arg make while in src
4) remove mkdir from clean & clobber rules

**Comment by goblinhack** [comment]
Cheers - all good ideas. See what you think now.

**Comment by hirdrac** [comment]
Ok. everything I listed above seems covered now but I've found a new issue.
Ramdisk files (src/ramdisk_data*) probably shouldn't be source controlled if you're generating them as part of the build.
(git versions currently don't match the generated files so I had to restore them before I could pull the latest changes)
Steps to fix this:
1) remove ramdisk_data.cpp & ramdisk_data_*.S files from git
2) add ramdisk files to .gitignore
3) add ramdisk file delete command to clobber rule

**Comment by goblinhack** [comment]
Good points :) done

**Comment by hirdrac** [comment]
> rm -rf $(BUILD_DIR) ramdisk_data.cpp $(ramdisk *.S)

so close!  just fix this file delete command (for ramdist_data*.S files)

**Comment by goblinhack** [comment]
got it - thanks!

**Comment by hirdrac** [comment]
I think this is good enough for now.  It's still required to manually run RUNME if src/Makefile.base is changed - a rule could be added to the root Makefile to do that automatically but I don't know if that would cause some other problems.

**Comment by goblinhack** [comment]
I don't add new files too often - but now it is using a wildcard list, that
helps even with that.
Thanks for the help Richard

Neil

**Comment by hirdrac** [comment]
Glad to help.  Some final clean-up you may want to do:
1) remove build/third-party/makedepend-1.0.5.tar.gz
2) remove makedepend install command from README.md
3) move src/Makefile.base to build/ with appropriate changes to build/build.sh  (just a personal preference - all build stuff in one place and src/ is already pretty full)

**Comment by goblinhack** [comment]
1 & 2 ack. 3 I kinda like the Makefile to be with the src

Thanks for the help Richard - your suggestions really improved the make
process
