### ISSUE TITLE
minor build issue

### ISSUE THREAD

**Issue by hirdrac** [goblinhack/zorbash#4]
I upgraded my system to Fedora 35 and its newer python version uncovered some minor issues.

1) build/build.sh creates these files so they should be removed from source control:
   * build/windows/python.version.sh
   * build/windows/windows.xml
2) .gitignore has the wrong path for these files as well.  These .gitignore changes are needed:
   * windows/python.version.sh -> build/windows/python.version.sh
   * windows/windows.xml -> build/windows/windows.xml

**Comment by goblinhack** [comment]
Cheers Richard -fixed
