### ISSUE TITLE
fixes needed for libstdc++ v12

### ISSUE THREAD

**Issue by hirdrac** [goblinhack/zorbash#5]
Are you accepting pull requests?  I have some fixes for compile errors & warnings I found when I upgraded to gcc 12 (which includes libstdc++)

Here's my 'git diff' output in case you would rather handle the fixes yourself:
diff --git a/src/my_range.hpp b/src/my_range.hpp
index 51a9f711b..b2dba9abd 100644
--- a/src/my_range.hpp
+++ b/src/my_range.hpp
@@ -5,6 +5,8 @@
 
 #pragma once
 #include <vector>
+#include <algorithm>
+#include <random>
 
 //
 // Create a vector of numbers
@@ -27,8 +29,6 @@ template < class T > std::vector< T > make_range(T start, T stop)
 //
 // Create a vector of numbers and then shuffle them
 //
-#include <algorithm>
-#include <random>
 extern std::default_random_engine     rng;
 template < class T > std::vector< T > make_shuffled_range(const size_t how_many)
 {

diff --git a/src/my_wid.hpp b/src/my_wid.hpp
index d412cfc72..96ddd3eaa 100644
--- a/src/my_wid.hpp
+++ b/src/my_wid.hpp
@@ -308,7 +308,7 @@ public:
   uint64_t key {};
 };
 
-struct tree_wid_key_cmp : public std::binary_function< class tree_wid_key, class tree_wid_key, bool > {
+struct tree_wid_key_cmp {
   bool operator()(const tree_wid_key &lhs, const tree_wid_key &rhs) const
   {
     if (lhs.priority < rhs.priority) {

diff --git a/src/string.cpp b/src/string.cpp
index 260115c3a..00d372f0c 100644
--- a/src/string.cpp
+++ b/src/string.cpp
@@ -7,6 +7,7 @@
 #include <libgen.h>
 #include <sstream>
 #include <string>
+#include <algorithm>
 
 #include "my_ptrcheck.hpp"
 #include "my_sdl.hpp"

**Comment by goblinhack** [comment]
Looks like the git diff above got garbled, Richard - if you don't mind, pls try a pull request ?

**Comment by hirdrac** [comment]
done - I have some more cleanup for the Makefile if you're interested as well

**Comment by goblinhack** [comment]
Sure - would love to have a look

**Comment by goblinhack** [comment]
thanks again Richard!
